# FROM sonarqube:latest
FROM sonarqube:enterprise

LABEL maintainer="xiagw <fxiaxiaoyu@gmail.com>"


# [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
# USER root
# RUN echo "sysctl -w vm.max_map_count=262144" >> /etc/sysctl.conf

